language: node_js
node_js: 14
cache: yarn
before_install:
  - npm i -g yarn
install:
  - yarn
script:
  - yarn status --endpoint $HASURA_GRAPHQL_ENDPOINT
deploy:
  skip_cleanup: false
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
