language: node_js
node_js: 14
cache: yarn
before_install:
  - npm i -g yarn
install:
  - yarn
script:
  - echo 'skip travis script stage'
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
