-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."semester" add column "is_current" boolean
--  null default 'false';
